# Generated by Django 2.2.7 on 2019-11-13 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='dateOfBirth',
        ),
        migrations.RemoveField(
            model_name='album',
            name='email',
        ),
        migrations.RemoveField(
            model_name='album',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='album',
            name='password',
        ),
    ]
