# Generated by Django 2.2.7 on 2019-11-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20191113_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='albumLogo',
            field=models.FileField(default=False, upload_to=''),
        ),
    ]
