# Generated by Django 2.2.7 on 2019-11-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_album_albumlogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musicians',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=250)),
                ('lastName', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=10)),
                ('educationQualifications', models.CharField(max_length=1000)),
            ],
        ),
    ]
